name: flutter_widgetz_example
description: flutter_widgetz example app.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_extensionz: 5.1.1
  flutter_themez: 4.0.1
  # flutter_themez:
  #   path: ../../flutter_themez
  # flutter_widgetz: 11.1.3
  flutter_widgetz:
    path: ../.

dev_dependencies:
  dart_lintz: 1.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/welcome/
